# Generated by Django 4.0.2 on 2022-02-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MB52',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=30)),
                ('division', models.CharField(max_length=20)),
                ('store', models.CharField(max_length=10)),
                ('store_level_deletion_indicator', models.CharField(max_length=15)),
                ('unit', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=5)),
                ('value_free_user', models.FloatField()),
                ('transit_transfer', models.FloatField()),
                ('transit_transfer_value', models.FloatField()),
                ('in_quality_control', models.FloatField()),
                ('value_quality_control', models.FloatField()),
                ('non_free_stock', models.FloatField()),
                ('non_free_value', models.FloatField()),
                ('blocked', models.FloatField()),
                ('blocked_stock_value', models.FloatField()),
                ('returns', models.FloatField()),
                ('blocked_return_stock_value', models.FloatField()),
            ],
        ),
    ]
