# Generated by Django 4.0.2 on 2022-02-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mb52',
            old_name='value_free_user',
            new_name='value_free_use',
        ),
    ]
