# Generated by Django 4.0.2 on 2022-02-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_value_free_user_mb52_value_free_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='mb52',
            name='for_free_use',
            field=models.FloatField(null=True),
        ),
    ]
