# Generated by Django 4.0.2 on 2022-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_mb52_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mb52',
            name='division',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mb52',
            name='material',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
