# Generated by Django 4.0.2 on 2022-06-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0036_z_sc_m_0002_z_sc_p_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z_sc_p_0004',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
    ]
