# Generated by Django 4.0.2 on 2022-06-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0037_alter_z_sc_p_0004_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z_sc_p_0004',
            name='updated_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
