# Generated by Django 4.0.2 on 2022-06-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0038_alter_z_sc_p_0004_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='z_sc_m_0002',
            old_name='num_material_fourn',
            new_name='num_material_fourn2',
        ),
        migrations.AddField(
            model_name='z_sc_m_0002',
            name='num_material_fourn1',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
