# Generated by Django 4.0.2 on 2022-06-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0039_rename_num_material_fourn_z_sc_m_0002_num_material_fourn2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z_sc_m_0002',
            name='tre',
            field=models.FloatField(null=True),
        ),
    ]
