# Generated by Django 4.0.2 on 2022-06-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0040_alter_z_sc_m_0002_tre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z_sc_m_0002',
            name='tps_fab_ext',
            field=models.FloatField(null=True),
        ),
    ]
