# Generated by Django 4.0.2 on 2022-06-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0041_alter_z_sc_m_0002_tps_fab_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z_sc_m_0002',
            name='num_material_fourn1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='z_sc_m_0002',
            name='num_material_fourn2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
